name: myapp
description: A exported flutter project from FUNCTION12


# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.13.0
  google_sign_in: ^6.1.0
  firebase_auth: ^4.6.1
  flutter_bloc: ^7.0.0
  equatable: ^2.0.3
  provider: ^6.0.1
  cloud_firestore: ^4.7.1
  firebase_database: ^10.0.1


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter



  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/page-1/images/battery.png
    - assets/page-1/images/wifi.png
    - assets/page-1/images/swipe-up.png
    - assets/page-1/images/cellular-connection.png
    - assets/page-1/images/cellular-connection-aQv.png
    - assets/page-1/images/rectangle-199.png
    - assets/page-1/images/rectangle-199-2ht.png
    - assets/page-1/images/icons8-copyright-24-1-1.png
    - assets/page-1/images/group.png
    - assets/page-1/images/battery-hrn.png
    - assets/page-1/images/group-8vi.png
    - assets/page-1/images/swipe-up-RdQ.png
    - assets/page-1/images/rectangle.png
    - assets/page-1/images/wifi-UZU.png
    - assets/page-1/images/fowardx-logo-1.png
    - assets/page-1/images/group-wLJ.png
    - assets/page-1/images/group-GsY.png
    - assets/page-1/images/group-x1k.png
    - assets/page-1/images/wifi-2yU.png
    - assets/page-1/images/battery-Hre.png
    - assets/page-1/images/cellular-connection-sZx.png
    - assets/page-1/images/profile.png
    - assets/page-1/images/group-91.png
    - assets/page-1/images/ic-search.png
    - assets/page-1/images/swipe-up-zvA.png
    - assets/page-1/images/cart.png
    - assets/page-1/images/rectangle-198.png
    - assets/page-1/images/group-91-jTc.png
    - assets/page-1/images/battery-Yp6.png
    - assets/page-1/images/rectangle-198-pb8.png
    - assets/page-1/images/cart-Drn.png
    - assets/page-1/images/mask.png
    - assets/page-1/images/group-93.png
    - assets/page-1/images/rectangle-5.png
    - assets/page-1/images/rectangle-43.png
    - assets/page-1/images/battery-yDG.png
    - assets/page-1/images/group-mi6.png
    - assets/page-1/images/tag.png
    - assets/page-1/images/group-93-tii.png
    - assets/page-1/images/cellular-connection-dZg.png
    - assets/page-1/images/rectangle-199-t7Y.png
    - assets/page-1/images/rectangle-29.png
    - assets/page-1/images/group-WJS.png
    - assets/page-1/images/rectangle-198-TXk.png
    - assets/page-1/images/vector.png
    - assets/page-1/images/swipe-up-Lmc.png
    - assets/page-1/images/rectangle-43-xSr.png
    - assets/page-1/images/rectangle-29-bMx.png
    - assets/page-1/images/rectangle-198-ZQS.png
    - assets/page-1/images/rectangle-198-TjL.png
    - assets/page-1/images/auto-group-hi2r.png
    - assets/page-1/images/group-91-Czr.png
    - assets/page-1/images/rectangle-9.png
    - assets/page-1/images/cellular-connection-G4n.png
    - assets/page-1/images/auto-group-nxpp.png
    - assets/page-1/images/group-JGN.png
    - assets/page-1/images/rectangle-198-hVY.png
    - assets/page-1/images/rectangle-199-e5L.png
    - assets/page-1/images/wifi-b1p.png
    - assets/page-1/images/tag-9Z8.png
    - assets/page-1/images/rectangle-198-v9t.png
    - assets/page-1/images/rectangle-198-xht.png
    - assets/page-1/images/group-12.png
    - assets/page-1/images/auto-group-lddp.png
    - assets/page-1/images/group-91-DEE.png
    - assets/page-1/images/group-8QN.png
    - assets/page-1/images/rectangle-199-bTt.png
    - assets/page-1/images/rectangle-Nez.png
    - assets/page-1/images/rectangle-199-6wg.png
    - assets/page-1/images/profile-xhU.png
    - assets/page-1/images/rectangle-Tc2.png
    - assets/page-1/images/group-K2E.png
    - assets/page-1/images/group-91-99Q.png
    - assets/page-1/images/favourites.png
    - assets/page-1/images/swipe-up-VWN.png
    - assets/page-1/images/tag-1dg.png
    - assets/page-1/images/auto-group-hrm8.png
    - assets/page-1/images/cellular-connection-jCJ.png
    - assets/page-1/images/rectangle-5-r22.png
    - assets/page-1/images/profile-QpE.png
    - assets/page-1/images/mask-vXg.png
    - assets/page-1/images/rectangle-29-6BG.png
    - assets/page-1/images/wifi-4Nz.png
    - assets/page-1/images/group-44W.png
    - assets/page-1/images/cellular-connection-NPg.png
    - assets/page-1/images/group-1N6.png
    - assets/page-1/images/group-ypi.png
    - assets/page-1/images/battery-x2S.png
    - assets/page-1/images/rectangle-199-iGW.png
    - assets/page-1/images/cart-gUE.png
    - assets/page-1/images/rectangle-9-RMp.png
    - assets/page-1/images/rectangle-29-B66.png
    - assets/page-1/images/swipe-up-y2v.png
    - assets/page-1/images/wifi-wWn.png
    - assets/page-1/images/tag-F82.png
    - assets/page-1/images/cellular-connection-fP4.png
    - assets/page-1/images/rectangle-5-kzA.png
    - assets/page-1/images/rectangle-aGn.png
    - assets/page-1/images/group-276.png
    - assets/page-1/images/favourites-BVQ.png
    - assets/page-1/images/favourites-YXG.png
    - assets/page-1/images/location.png
    - assets/page-1/images/auto-group-g3zy.png
    - assets/page-1/images/pin.png
    - assets/page-1/images/rectangle-YR4.png
    - assets/page-1/images/nounshopping-bag31351.png
    - assets/page-1/images/battery-nXQ.png
    - assets/page-1/images/divider.png
    - assets/page-1/images/divider-pgW.png
    - assets/page-1/images/icon-feather-package.png
    - assets/page-1/images/cellular-connection-dwk.png
    - assets/page-1/images/pin-dUS.png
    - assets/page-1/images/group-2FY.png
    - assets/page-1/images/x311.png
    - assets/page-1/images/rectangle-29-4dc.png
    - assets/page-1/images/auto-group-p6y4.png
    - assets/page-1/images/vector-9ee.png
    - assets/page-1/images/profile-xAa.png
    - assets/page-1/images/vector-gzJ.png
    - assets/page-1/images/group-ba6.png
    - assets/page-1/images/visa.png
    - assets/page-1/images/card-slider.png
    - assets/page-1/images/auto-group-agye.png
    - assets/page-1/images/favourites-6Ei.png
    - assets/page-1/images/mask-ioG.png
    - assets/page-1/images/battery-HKL.png
    - assets/page-1/images/cellular-connection-5XL.png
    - assets/page-1/images/rectangle-199-AHC.png
    - assets/page-1/images/profile-Vw4.png
    - assets/page-1/images/ic-search-Hmg.png
    - assets/page-1/images/vector-9s4.png
    - assets/page-1/images/wifi-WcN.png
    - assets/page-1/images/group-cqL.png
    - assets/page-1/images/group-91-kQW.png
    - assets/page-1/images/group-91-8bY.png
    - assets/page-1/images/arrow.png
    - assets/page-1/images/battery-uRG.png
    - assets/page-1/images/rectangle-29-N3G.png
    - assets/page-1/images/icon-awesome-check-circle.png
    - assets/page-1/images/swipe-up-566.png
    - assets/page-1/images/rectangle-29-2er.png
    - assets/page-1/images/cart-9q8.png
    - assets/page-1/images/profile-7QS.png
    - assets/page-1/images/group-dcJ.png
    - assets/page-1/images/group-98i.png
    - assets/page-1/images/group-91-scS.png
    - assets/page-1/images/mask-pNa.png
    - assets/page-1/images/swipe-up-nfQ.png
    - assets/page-1/images/rectangle-sw4.png
    - assets/page-1/images/vector-Vst.png
    - assets/page-1/images/battery-hsU.png
    - assets/page-1/images/ic-arrow.png
    - assets/page-1/images/ellipse-134.png
    - assets/page-1/images/card-slider-QpN.png
    - assets/page-1/images/rectangle-29-itW.png
    - assets/page-1/images/wifi-rYn.png
    - assets/page-1/images/rectangle-5-Xk2.png
    - assets/page-1/images/combined-shape.png
    - assets/page-1/images/icon-awesome-check-circle-xzJ.png
    - assets/page-1/images/vector-XUJ.png
    - assets/page-1/images/favourites-XLS.png
    - assets/page-1/images/vector-o3c.png
    - assets/page-1/images/bg.png
    - assets/page-1/images/group-Ypn.png
    - assets/page-1/images/wifi-S5c.png
    - assets/page-1/images/date-selected.png
    - assets/page-1/images/vector-ahU.png
    - assets/page-1/images/wifi-3GA.png
    - assets/page-1/images/auto-group-sz9y.png
    - assets/page-1/images/vector-9pA.png
    - assets/page-1/images/frame.png
    - assets/page-1/images/rectangle-pnz.png
    - assets/page-1/images/cart-Bq8.png
    - assets/page-1/images/rectangle-5-ePp.png
    - assets/page-1/images/combined-shape-w26.png
    - assets/page-1/images/cellular-connection-Kgi.png
    - assets/page-1/images/icon-awesome-check-circle-Epv.png
    - assets/page-1/images/cellular-connection-g5t.png
    - assets/page-1/images/date-selected-JVC.png
    - assets/page-1/images/ellipse-134-xL6.png
    - assets/page-1/images/date-selected-qdp.png
    - assets/page-1/images/group-f3k.png
    - assets/page-1/images/vector-61C.png
    - assets/page-1/images/card-slider-nht.png
    - assets/page-1/images/battery-CyC.png
    - assets/page-1/images/rectangle-wyx.png
    - assets/page-1/images/favourites-D5Y.png
    - assets/page-1/images/icon-awesome-check-circle-ovE.png
    - assets/page-1/images/line.png
    - assets/page-1/images/favourites-8vS.png
    - assets/page-1/images/cellular-connection-k5t.png
    - assets/page-1/images/combined-shape-uZg.png
    - assets/page-1/images/auto-group-ryus.png
    - assets/page-1/images/rectangle-hjt.png
    - assets/page-1/images/arrow-QX8.png
    - assets/page-1/images/card-slider-xnr.png
    - assets/page-1/images/visa-4ir.png
    - assets/page-1/images/rectangle-5-7U2.png
    - assets/page-1/images/rectangle-5-i7g.png
    - assets/page-1/images/vector-d7c.png
    - assets/page-1/images/wifi-v4N.png
    - assets/page-1/images/ellipse-134-L3Y.png
    - assets/page-1/images/line-R82.png
    - assets/page-1/images/wifi-xte.png
    - assets/page-1/images/cellular-connection-trA.png
    - assets/page-1/images/image-4.png
    - assets/page-1/images/vector-T3t.png
    - assets/page-1/images/battery-uR8.png
    - assets/page-1/images/vector-eaz.png
    - assets/page-1/images/profile-A8e.png
    - assets/page-1/images/wifi-j7C.png
    - assets/page-1/images/image-3.png
    - assets/page-1/images/chevron.png
    - assets/page-1/images/cellular-connection-Boc.png
    - assets/page-1/images/battery-8D4.png
    - assets/page-1/images/cellular-connection-Zkr.png
    - assets/page-1/images/battery-b98.png
    - assets/page-1/images/cart-uvW.png
    - assets/page-1/images/swipe-up-rar.png
    - assets/page-1/images/cart-2zS.png
    - assets/page-1/images/battery-5Sv.png
    - assets/page-1/images/combined-shape-n6S.png
    - assets/page-1/images/wifi-jGa.png
    - assets/page-1/images/group-s1Q.png
    - assets/page-1/images/vector-uCz.png
    - assets/page-1/images/visa-TkJ.png
    - assets/page-1/images/vector-DzN.png
    - assets/page-1/images/vector-zES.png
    - assets/page-1/images/battery-MKt.png
    - assets/page-1/images/arrow-4k6.png
    - assets/page-1/images/auto-group-duyw.png
    - assets/page-1/images/wifi-Wrz.png
    - assets/page-1/images/visa-dRp.png
    - assets/page-1/images/swipe-up-znA.png
    - assets/page-1/images/swipe-up-N8W.png
    - assets/page-1/images/profile-64W.png
    - assets/page-1/images/chevron-9yp.png
    - assets/page-1/images/vector-7ve.png
    - assets/page-1/images/group-sQ2.png
    - assets/page-1/images/group-33c.png
    - assets/page-1/images/ellipse-134-CSJ.png
    - assets/page-1/images/cart-kii.png
    - assets/page-1/images/chevron-QSS.png
    - assets/page-1/images/chevron-Fci.png
    - assets/page-1/images/swipe-up-r8v.png
    - assets/page-1/images/wifi-dYr.png
    - assets/page-1/images/cellular-connection-xb8.png
    - assets/page-1/images/chevron-Tnn.png
    - assets/page-1/images/chevron-Tpa.png
    - assets/page-1/images/chevron-Dfk.png
    - assets/page-1/images/chevron-zHU.png
    - assets/page-1/images/group-bVG.png
    - assets/page-1/images/fowardx-logo-2.png
    - assets/page-1/images/a-2.png
    - assets/page-1/images/chevron-fyG.png
    - assets/page-1/images/chevron-3Wv.png
    - assets/page-1/images/chevron-eyt.png
    - assets/page-1/images/rectangle-5-rV4.png
    - assets/page-1/images/swipe-up-wZg.png
    - assets/page-1/images/group-91-v1U.png
    - assets/page-1/images/auto-group-8pqz.png
    - assets/page-1/images/rectangle-43-Gyt.png
    - assets/page-1/images/icons8-google-48-3.png
    - assets/page-1/images/battery-iWa.png
    - assets/page-1/images/cellular-connection-TiN.png
    - assets/page-1/images/group-f6E.png
    - assets/page-1/images/group-x4e.png
    - assets/page-1/images/a-1.png
    - assets/page-1/images/swipe-up-QbG.png
    - assets/page-1/images/favourites-tA2.png
    - assets/page-1/images/auto-group-vyq2.png
    - assets/page-1/images/wifi-9aN.png
    - assets/page-1/images/swipe-up-Ciz.png
    - assets/page-1/images/rectangle-650.png
    - assets/page-1/images/swipe-up-yNv.png
    - assets/page-1/images/group-mi6-MXt.png
    - assets/page-1/images/cart-Yzr.png
    - assets/page-1/images/wifi-qK4.png
    - assets/page-1/images/chevron-Fu8.png
    - assets/page-1/images/chevron-qdg.png
    - assets/page-1/images/chevron-xXG.png
    - assets/page-1/images/chevron-USz.png
    - assets/page-1/images/battery-apn.png
    - assets/page-1/images/chevron-31Y.png
    - assets/page-1/images/chevron-ji6.png
    - assets/page-1/images/chevron-18J.png
    - assets/page-1/images/a-1-VTc.png
    - assets/page-1/images/rectangle-649.png
    - assets/page-1/images/a-1-kUe.png
    - assets/page-1/images/welcome-1-bg.png
    - assets/page-1/images/a-1-NvJ.png
    - assets/page-1/images/rectangle-648.png
    - assets/page-1/images/img.png
    - assets/page-1/images/img2.png
    - assets/page-1/images/img3.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
